# Generated by Django 4.1.4 on 2024-01-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_doctor_geeks_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/annotated_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('temperature_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
