# Generated by Django 4.1.4 on 2024-01-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_annotatedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('appointed_doctor', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=10)),
                ('center', models.CharField(max_length=50)),
                ('report_generation_date', models.DateField()),
                ('scan_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='AnnotatedImage',
        ),
    ]
