# Generated by Django 4.1.4 on 2024-02-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_userform_delete_annotatedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='id',
        ),
        migrations.AddField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=47985, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='center',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10),
        ),
    ]
