# Generated by Django 4.1.4 on 2024-02-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_userform_id_userform_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=94746, primary_key=True, serialize=False, unique=True),
        ),
    ]
