# Generated by Django 4.1.4 on 2024-02-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_image_uploader_alter_userform_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=15291, primary_key=True, serialize=False, unique=True),
        ),
    ]
