# Generated by Django 4.1.4 on 2024-02-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_userform_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(default='default_status', max_length=100),
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=75117, primary_key=True, serialize=False, unique=True),
        ),
    ]
