# Generated by Django 4.1.4 on 2024-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_image_status_alter_userform_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=46526, primary_key=True, serialize=False, unique=True),
        ),
    ]
