# Generated by Django 4.1.4 on 2024-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_userimage_remove_image_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='userimage',
            name='center_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='left_45_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='left_90_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='right_45_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userimage',
            name='right_90_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='patient_id',
            field=models.IntegerField(default=89854, primary_key=True, serialize=False, unique=True),
        ),
    ]
