# Generated by Django 4.1.4 on 2024-02-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_userimage_image_remove_userimage_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='patient_id',
            field=models.IntegerField(default=30483, primary_key=True, serialize=False, unique=True),
        ),
    ]
