# Generated by Django 4.1.4 on 2024-02-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_image_user_form_alter_userform_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user_form',
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=30872, primary_key=True, serialize=False, unique=True),
        ),
    ]
