# Generated by Django 4.1.4 on 2024-02-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_image_user_form_alter_userform_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_user_form', to='main.image'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=33625, primary_key=True, serialize=False, unique=True),
        ),
    ]
