# Generated by Django 4.1.4 on 2024-02-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_userform_appointed_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(upload_to='pdf_reports/')),
            ],
        ),
        migrations.AlterField(
            model_name='userform',
            name='appointed_doctor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=70995, primary_key=True, serialize=False, unique=True),
        ),
    ]
