# Generated by Django 4.1.4 on 2024-02-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_userform_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=53120, primary_key=True, serialize=False, unique=True),
        ),
    ]
