# Generated by Django 4.1.4 on 2024-02-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_image_is_processed_alter_userform_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_uploads/'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=48297, primary_key=True, serialize=False, unique=True),
        ),
    ]
