# Generated by Django 4.1.4 on 2024-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_userform_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='image',
            name='processed_image',
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=16273, primary_key=True, serialize=False, unique=True),
        ),
    ]
