# Generated by Django 4.1.4 on 2024-02-26 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_image_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfreport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=54628, primary_key=True, serialize=False, unique=True),
        ),
    ]
