# Generated by Django 4.2.4 on 2024-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_pdfreport_doctor_alter_userform_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='patient_id',
            field=models.IntegerField(default=54342, primary_key=True, serialize=False, unique=True),
        ),
    ]
